//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.03 at 03:39:58 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://nokiaspstraining.project/demo/wsdl", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package project.nokiaspstraining.demo.wsdl;
